ippgroup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include("website.urls", namespace="website")),
    url(r'^admin/', admin.site.urls),
    url(r'^newsletter/', include('newsletter.urls', namespace="newsletters")),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<site_id>\d+)/(?P<slug>.+)/', include("articles.urls", namespace="articles")),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^signup/$', views.signup_view, name="signup"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"><!--<![endif]-->
<head>
	<!-- Basic Page Needs -->
	<meta charset="utf-8">
	<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
	<title>{% block title %}{% endblock title %} | Indian Printer Publisher (IPP) Group</title>
	<meta name="description" content="{{description}}">
	<meta name="keywords" content="{{keywords}}">
	<meta name="author" content="Delhi Nerds">

	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Bootstrap  -->
	<link rel="stylesheet" type="text/css" href="{% static "stylesheets/bootstrap.css" %}" >

	<!-- Theme Style -->
	<link rel="stylesheet" type="text/css" href="{% static "stylesheets/style.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "custom.css" %}">

	<!-- Colors -->
	<link rel="stylesheet" type="text/css" href="{% static "stylesheets/colors/color1.css" %}" id="colors">

	<!-- Animation Style -->
	<link rel="stylesheet" type="text/css" href="{% static "stylesheets/animate.css" %}">

	<!-- Google Fonts
	<link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700' rel='stylesheet' type='text/css'>-->

	<!-- Favicon and touch icons  -->
	<link href="{% static "icon/apple-touch-icon-144-precomposed.png" %}" rel="apple-touch-icon-precomposed" sizes="144x144">
	<link href="{% static "icon/apple-touch-icon-114-precomposed.png" %}" rel="apple-touch-icon-precomposed" sizes="114x114">
	<link href="{% static "icon/apple-touch-icon-72-precomposed.png" %}" rel="apple-touch-icon-precomposed" sizes="72x72">
	<link href="{% static "icon/apple-touch-icon-57-precomposed.png" %}" rel="apple-touch-icon-precomposed">
	<link href="{% static "icon/favicon.png" %}" rel="shortcut icon">

	<!--[if lt IE 9]>
		<script src="javascript/html5shiv.js"></script>
		<script src="javascript/respond.min.js"></script>
	<![endif]-->
</head>

<body>

{% include "header.html" %}

{% block content %}
{% endblock content %}

{% include "footer.html" %}
{% include "modals.html" %}

<!-- Go Top -->
<a class="go-top">
  <i class="fa fa-chevron-up"></i>
</a>

<!-- Javascript -->
<script type="text/javascript" src="{% static "javascript/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery.easing.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/matchMedia.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery-waypoints.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery.flexslider.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery.transit.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery.leanModal.min.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery.tweet.min.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery.cookie.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/jquery.doubletaptogo.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/smoothscroll.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/main.js" %}"></script>
<script type="text/javascript" src="{% static "javascript/auth.js" %}"></script>
</body>


</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer id="footer">
  <div class="footer-widgets">
    <div class="container">
      <div class="row">
        <div class="col-md-4 gn-animation" data-animation="fadeInUp" data-animation-delay="0" data-animation-offset="75%">
          <div class="widget widget-brand">
            <div class="logo logo-footer">
              <a href="{% url "website:index" %}"><img src="{% static "tlogo.png" %}" /></a>
            </div>
            <p>This pays especially well in technology, where you earn a premium for working fast.</p>
          </div><!-- /.widget-brand -->
          <div class="widget widget-social">
            <h5 class="widget-title">Follow Us</h5>
            <div class="social-list">
              <a href="#"><img src="{% static "images/facebook.svg" %}" alt="image"></a>
              <a href="#"><img src="{% static "images/twitter.svg" %}" alt="image"></a>
              <a href="#"><img src="{% static "images/youtube.svg" %}" alt="image"></a>
              <a href="#"><img src="{% static "images/dribbble.svg" %}" alt="image"></a>
            </div>
            <a class="email" href="#">info@ippgroup.in</a>
          </div><!-- /.widget-social -->
        </div><!-- /.col-md-4 -->
        <div class="col-md-4 gn-animation" data-animation="fadeInUp" data-animation-delay="0.2s" data-animation-offset="75%">
          <div class="widget widget-twitter">
            <h5 class="widget-title">Twitter</h5>
            <div class="latest-tweets" data-number="3" data-username="envato" data-modpath="twitter/index.html"></div>
          </div><!-- /.widget-twitter -->
        </div><!-- /.col-md-4 -->
        <div class="col-md-2 gn-animation" data-animation="fadeInUp" data-animation-delay="0.4s" data-animation-offset="75%">
          <div class="widget widget-list">
            <h5 class="widget-title">Main</h5>
            <ul class="links-list">
              <li><a href="#">Mustreads</a></li>
              <li><a href="#">Tech</a></li>
              <li><a href="#">Business</a></li>
              <li><a href="#">Entertainment</a></li>
              <li><a href="#">Social Media</a></li>
            </ul>
          </div><!-- /.widget-list -->
        </div><!-- /.col-md-2 -->
        <div class="col-md-2 gn-animation" data-animation="fadeInUp" data-animation-delay="0.6s" data-animation-offset="75%">
          <div class="widget widget-list">
            <h5 class="widget-title">About Us</h5>
            <ul class="links-list">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Our Team</a></li>
              <li><a href="#">Careers </a></li>
              <li><a href="#">Advertise</a></li>
              <li><a href="#">Copyright</a></li>
            </ul>
          </div><!-- /.widget-list -->
        </div><!-- /.col-md-2 -->
      </div><!-- /.row -->
    </div><!-- /.container -->
  </div><!-- /.footer-widgets -->
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          &copy; 2017. All rights reserved by Indian Printer Publisher Group and it's affiliates. Designed and developed by <a href="http://www.delhinerds.com" target="_blank">Delhi Nerds</a>.
        </div><!-- /.col-md-12 -->
      </div><!-- /.row -->
    </div><!-- /.container -->
  </div>
</footer>

templates/header.html
{% load staticfiles %}

<!-- Header -->
<header id="header" class="header">
  <div class="top-wrap">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
                <div id="logo" class="logo">
          <a href="index.html" rel="home" title="home">
            <img src="{% static "tlogo.png" %}" style="" alt="Good News" />
          </a>
              </div>
              <div class="follow-us">
                <div class="follow-title">
                  Follow Us
                </div>
                <ul class="social-links">
                  <li class="facebook"><a href="#">Follow us on Facebook</a></li>
                  <li class="twitter"><a href="#">Follow us on Twitter</a></li>
                  <li class="google"><a href="#">Follow us on Google</a></li>
                  <li class="linkedin"><a href="#">Follow us on Linkedin</a></li>
                  <li class="pinterest"><a href="#">Follow us on Pinterest</a></li>
                </ul>
              </div>
            </div><!-- /.col-md-6 -->
            <div class="col-md-6">
              <div class="btn-menu"></div><!-- //mobile menu button -->
              <div class="member-area">
                {% if request.user.is_authenticated %}
                 <span>Welcome {{user.first_name}} {{user.last_name}}</span>
                 <span class="signup-popup"><a href="#">My Account</a></span>
                 <span class="login-popup"><a href="{% url "website:logout" %}">Logout</a></span>
                {% else %}
                 <span class="login-popup"><a href="#login-modal">Login</a></span>
                 <span class="signup-popup"><a href="#signup-modal">Become a member</a></span>
                {% endif %}
              </div>
            </div><!-- /.col-md-6 -->
          </div><!-- /.row -->
       </div><!-- /.container -->
  </div><!-- /.top-wrap -->

  {% if not request.resolver_match.view_name == "website:index" %}
    <div class="header-wrap">
     <div class="container">
        <div class="row">
        <div class="col-md-9">
          <nav id="mainnav" class="mainnav">
            <ul class="menu">
              <li><a href="{% url "website:articles:index" site.site.pk site.site.name|slugify %}">Home</a></li>
              <li class="has-children"><a href="#">Categories</a>
                <ul class="sub-menu">
                  {% for each in categories %}
                    <li><a href="{% url "website:articles:category" site.site.pk site.site.name|slugify each.pk each.name|slugify %}">{{each.name}}</a></li>
                  {% endfor %}
                </ul><!-- /.submenu -->
              </li>
              <li><a href="category.html">About Us</a></li>
              <li><a href="ui-elements.html">Contact Us</a></li>
            </ul><!-- /.menu -->
          </nav><!-- /nav -->
        </div><!-- /.col-md-9 -->
        <div class="col-md-3">
          <div class="search-wrap">
            <div class="search-icon"></div><!-- //mobile search button -->
            <form action="#" id="searchform" class="search-form" method="get" role="search">
              <input type="text" id="s" placeholder="Search" class="search-field">
              <input type="submit" value="&#xf002;" id="searchsubmit" class="search-submit">
              <a class="search-close" href="#"><i class="fa fa-times-circle"></i></a>
            </form>
          </div><!-- /.search-wrap -->
        </div><!-- /.col-md-3 -->
        </div><!-- /.row -->
     </div><!-- /.container -->
    </div><!-- /.header-wrap -->
    {% endif %}
</header>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Home
{% endblock title %}


{% block content %}
	<section id="main">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="gnSlider gn-animation" data-animation="fadeInUp" data-animation-delay="0" data-animation-offset="75%">
							<div class="flex-container">
									<div class="flexslider loading">
											<ul class="slides">
												{% for each in sites %}
													<li>
															<div class="item-wrap">
																<a href="{% url "website:articles:index" each.site.pk each.site.name|slugify %}"><img src="{{each.image.url}}" alt="image"></a>																	
																	<p class="item" data-bottomtext="0">{{each.about|safe}}</p>
															</div>
													</li>
												{% endfor %}
											</ul>
									</div>
							</div>
					</div><!-- /.gnSlider -->
				</div>
			</div>
		</div>
	</section>
{% endblock content %}